### ISSUE TITLE
How to for obfuscate Evilginx and Gophish ?

### ISSUE THREAD

**Issue by Dazmed707** [D00Movenok/HTMLSmuggler#1]
Need starat attack RED TEAM, and need protect my server Evilginx and Gophish.

**Comment by D00Movenok** [comment]
The full explanation what is HTML Smuggling may be found [here](https://outflank.nl/blog/2018/08/14/html-smuggling-explained/), please, read it carefully.

The main idea of html smuggling is to deliver your payload (e.g. executable, .iso, etc.) within html/js/svg/etc., not to obfuscate Evilginx and/or Gophish pages. However you may try to embed HTML smuggled payload into your pages (see examples in readme) within gophish (nice idea) or evilginx (seems useless)

If you need to protect your pages from bots/sandboxes/etc., you may use another my tool [BounceBack](https://github.com/D00Movenok/BounceBack).

If I misunderstood the question, please ask it more precisely.

**Comment by Dazmed707** [comment]
I wanted to see if I followed this protection method, I have also seen BB, in any case, would I only use BB?

I have researched and found these alternatives, BB would be enough or would I have to add one of these extra methods.

https://github.com/puzzlepeaches/sneaky_gophish?tab=readme-ov-file

https://www.jackphilipbutton.com/post/how-to-protect-evilginx-using-cloudflare-and-html-obfuscation

**Comment by D00Movenok** [comment]
Sneaky gophish removes some "backdoors" that can be used to fingerprint gophish, so it's a good idea to use sneaky_gophish.

Idea about using cloudflare may be nice, if you enable bot protection and because cf servers are already trusted, but think twice -  how many clicks potential victim need to bypass bot protection captcha? :)

The idea of BB is to filter out some of the unwanted traffic (for example, sandboxes or bots) from your service using multiple filters (check wiki), it is really useful for protection agains sandboxes and mail gateways.

So, if I were you, I'd use both the sneaky_gophish and the BB, maybe cloudflare, but html obfuscation is overkill for evilginx case.

**Comment by Dazmed707** [comment]
I have thought about using these combinations

Test campaign #1: Keep all IOCs

Test campaign #2: use autosneakphish + [sneakgophish](https://www.patreon.com/posts/custom-modded-96580107?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link) + Amazon SES




I also had this project at hand, but I was looking at BB

https://github.com/WhiteOakSecurity/autosneakphish

In addition, it would be advisable to use one server for gophish and another for evilginx, or everything would be installed in one.

If it is separately, I would have to install BB on each one the same, and what hardware would be recommended for everything to run normally, now among so much material, I am a little confused in the order of installation and what will guarantee me a red team attack up for a few months.

**Comment by Dazmed707** [comment]
okey, i run in AWS a VPS recomended u.

and have other question, evilginx not support recaptcha

![image](https://github.com/D00Movenok/HTMLSmuggler/assets/35184132/b079e7b1-3240-4fca-a96b-a0f4e8e12555)

i read this, and no konw implement ? u have solution?

https://github.com/An0nUD4Y/Evilginx2-Phishlets/blob/master/README.md#google-recaptcha-bypass-by-desire

**Comment by D00Movenok** [comment]
No, I don't have a public solution
